version: "3.4"

services:
  frontend:
    container_name: frontend
    depends_on:
      - backend
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
  backend:
    container_name: backend
    depends_on:
      - db
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    
  db:
      container_name: database
      image: postgres:15-alpine
      restart: always
      env_file:
        - .env
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: nest-pgadmin4
    env_file:
      - .env
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - ./pgadmin:/var/lib/pgadmin