global:
  scrape_interval:      10s
  evaluation_interval:  10s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093


scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'django'
    scrape_interval: 15s
    static_configs:
      - targets: ['django:8000']
