# Generated by Django 5.0.1 on 2024-01-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcendenceuser',
            name='profile_picture',
            field=models.CharField(default='default.jpg', max_length=100),
        ),
    ]
