# Generated by Django 5.0.1 on 2024-01-30 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcendenceuser',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transcendenceuser',
            name='score',
            field=models.IntegerField(default=500),
        ),
    ]
