# Generated by Django 5.0.1 on 2024-01-28 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_transcendenceuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcendenceuser',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transcendenceuser',
            name='score',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='transcendenceuser',
            name='profile_picture',
            field=models.CharField(default='default.webp', max_length=100),
        ),
    ]
