# Generated by Django 5.0.1 on 2024-02-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_image_transcendenceuser_pfp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcendenceuser',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='transcendenceuser',
            name='pfp',
        ),
    ]
