# Generated by Django 5.0.1 on 2024-02-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_transcendenceuser_last_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcendenceuser',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transcendenceuser',
            name='pfp',
            field=models.ImageField(default='default.webp', upload_to='pfp'),
        ),
    ]
