# Generated by Django 5.0.1 on 2024-01-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_transcendenceuser_friends_transcendenceuser_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcendenceuser',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
