# Generated by Django 4.2.7 on 2023-12-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_transcendenceuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcendenceuser',
            name='username',
            field=models.CharField(default='default_username', max_length=55, unique=True),
            preserve_default=False,
        ),
    ]
