apiVersion: 1

providers:
  - name: 'default'
    orgId: 1
    folder: ''
    type: file
    disableDeletion: false
    updateIntervalSeconds: 3600 # How often Grafana will scan for changed dashboards
    options:
      path: /usr/share/grafana/public/mydashboards
