# Generated by Django 5.0.2 on 2024-02-24 01:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchLog',
            new_name='MatchEntry',
        ),
    ]
