# Generated by Django 5.0.2 on 2024-02-24 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_history', '0002_rename_matchlog_matchentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='matchentry',
            name='score_diff',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='matchentry',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_lost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchentry',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
