# Generated by Django 5.0.2 on 2024-02-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_history', '0003_matchentry_date_matchentry_score_diff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchentry',
            name='score_diff',
        ),
    ]
